### ISSUE TITLE
Can we get how to setup and run this project locally? 

### ISSUE THREAD

**Issue by bhupendra-nitt** [Ziggeo/react-ziggeo#1]
I am a ziggeo user and I want to contribute to the project but couldn't find a wiki. It would be of great help if you can provide with the same.

**Comment by Bane-D** [comment]
Hi,

Our React SDK is a new one so it does not yet contain as much info as others do however we do have a demo that should help with the same.

You can find it here: https://github.com/Ziggeo/react-ziggeo/tree/master/demo

Now the local setup is nicely explained here: https://facebook.github.io/react/docs/installation.html so I would suggest checking that page and clicking on the "Create a New App" tab to see the info.

There is a presumption that you have Node installed on your system, if not you would need it to create app, however you can always create HTML pages manually if you want to test something instead.

If you did not make use the create-react-app it is good to make it global so you would do it like so:
`npm install -g create-react-app`

Now in general these steps should help you get started:
1. go to a directory where you will have your project and open console (with that as working dir)
2. run the following code in terminal / console
```
create-react-app my_cool_app
cd my_cool_app
npm start
```
After running npm start, you can open your browser and go to http://localhost:3000/ which will show you the results of your changes as you make them.

Please check it out and let us know how it goes for you :)

Regards,
Bane
