### ISSUE TITLE
Recorder select_camera is not working in Firefox and Safari

### ISSUE THREAD

**Issue by clement-lta** [Ziggeo/react-ziggeo#100]
Hi! I'm using Recorder and I want to change the camera device when changing my selection. I got my deviceId but I can not change the device by the `select_camera` method on Firefox and Safari.

this is the script when I change the device on my select:
```javascript
recorder.select_camera(device.deviceId);
```

This only works on Chrome. but Firefox and Safari does not.
Below is the script when I use ziggeo.js and it works, but when using react-ziggeo, it does not. You can also run react-ziggeo example in Firefox run try to switch camera in control of recorder

https://stackblitz.com/edit/web-platform-sdaqza?file=index.html

**Comment by Bane-D** [comment]
Hi Tuan,

Looking at the page it seems to be the JS code, not React one. 

I would just like to confirm that if you use the JS code it will work for you in Safari, Chrome and Firefox. Is that correct? If so then the issue is only present on Safari and Firefox when you use the React codes.

Since you mention Safari, I am guessing you are using Mac OS, so wanted to check if you had a chance to try the same on some other OS (Windows or some Unix based system)?

* It is fine if not, and while it should not make much of a difference if we can not recreate something on our system, we like to try on something more close to where the issue has shown itself.

In that light, it would be useful if you would share the React codes you had used for the recorder (fine to remove the app token of course).

**Comment by clement-lta** [comment]
Hi @Bane-D ! Thanks for your answer.

> I would just like to confirm that if you use the JS code it will work for you in Safari, Chrome and Firefox. Is that correct? If so then the issue is only present on Safari and Firefox when you use the React codes.

-> YES

> Since you mention Safari, I am guessing you are using Mac OS, so wanted to check if you had a chance to try the same on some other OS (Windows or some Unix based system)?

-> YES, I used Mac OS. Sorry but I don't have a Linux device. my boss has a Window device but it does not work on Safari / Firefox

This is React code I used:

```js
  <ZiggeoRecorder
        skipinitial
        apiKey=
        height="100%"
        width="100%"
        allowcancel
        webrtc_streaming_if_necessary
        theme="default"
        themecolor="default"
        allowrecord
        allowupload={false}
        timelimit="240"
        faceoutline={false}
        skipinitialonrerecord
        picksnapshots={false}
        gallerysnapshots={false}
        countdown={3}
        manualsubmit
        onRef={collectRef}
        recordingwidth={640}
        recordingheight={480}
      />
```

**Comment by Bane-D** [comment]
Great, thank you for the info Tuan.

Just as a common suspect, can you try the same codes without `skipinitial` being set?

Some browsers will be a bit more strict about the use case where skipinitial is set as true. While I am hoping it would make a difference, it is quite possible that we will need to look into this some more.

**Comment by clement-lta** [comment]
@Bane-D thank you! I tried many cases including your case. but it does not work

**Comment by Bane-D** [comment]
OK, thank you for the feedback Tuan.

One of my colleagues with more experience with React will try reach out after trying to recreate the issue on their side. The only thing that I would like to ask you which could help them is if you got any error in the console when this happens?

It might direct them towards some specific part of our React SDK to look into.

**Comment by clement-lta** [comment]
Yeah. sorry for the omission when raising an issue
There is no error in console when it happen

**Comment by Bane-D** [comment]
That is perfectly fine Tuan, thank you for the details.

Best to wait for my colleague to look into this more and follow up with you afterwards.

Thank you for all the details so far.

**Comment by clement-lta** [comment]
Thank you so much @Bane-D

**Comment by clement-lta** [comment]
Hi @Bane-D Can you help me to check with your friend about this ticket? 😄 Thank you!

**Comment by Bane-D** [comment]
Hi Tuan,

Thank you for the wait. He was not available during the weekend so he was not able to get back to you however I see his notes, he is looking into this and will reach out. Looks like we might need to add something into React SDK, leaving it to him to follow up with more info once he had a closer look. :)

**Comment by carstenschaefer** [comment]
Good Day!

Any news on this from the Ziggeo React guy ?

**Comment by bansal84k** [comment]
Hi @tuananhl 

Could you please confirm if the code that you provided works in plain JS on FF for you? I tried using your code and it worked fine for me on Chrome but not on FF. 

Could you please also send me your full react code that worked for you on Chrome?

Regards
Karan

**Comment by clement-lta** [comment]
> Hi @tuananhl
> 
> Could you please confirm if the code that you provided works in plain JS on FF for you? I tried using your code and it worked fine for me on Chrome but not on FF.
> 
> Could you please also send me your full react code that worked for you on Chrome?
> 
> Regards Karan

Hi @bansal84k 
Thanks for your reply. you can refer to this [comment](https://github.com/Ziggeo/react-ziggeo/issues/100#issuecomment-1278091978) to see what I use the ziggeo in React

**Comment by clement-lta** [comment]
Sorry but any news on this issue? @Bane-D @bansal84k ?

**Comment by Bane-D** [comment]
Hi Tuan,

Looking into this for you.

**Comment by clement-lta** [comment]
Hi @Bane-D thanks for your reply!
any update on this issue?

**Comment by clement-lta** [comment]
@Bane-D I updated into r41 and it works now. Thank you for your support!
