### ISSUE TITLE
Error: 'with' in strict mode when building a react application

### ISSUE THREAD

**Issue by robingronlund** [Ziggeo/react-ziggeo#104]
I have a setup with a CRA-built react-app using typescript which uses the `react-ziggeo` npm package. Using your video recorder works and I'm able to record, upload and play said videos.

But my error comes when I run my build scripts. I use `Rollup` to produce a bundled js file. While having the `ZiggeoVideoRecorder` or `ZiggeoVideoPlayer` as part of my app I get this output:

`[!] (plugin rpt2) Error: 'with' in strict mode (11969:1221518) in ./node_modules/react-ziggeo/build/index.js`

Not really sure how to get around this, if you need more information on my setup I'm more then willing to provide it.

**Comment by Bane-D** [comment]
Hi there Robin,

Thank you for writing about this. We have removed the use of `with` from our scripts a bit back, however after your report we have found that there are still few uses of the same in the framework we use - [BetaJS](https://betajs.com/).

We are looking to sort this out so that there are no errors raised due to same.

**Comment by robingronlund** [comment]
> Hi there Robin,
> 
> Thank you for writing about this. We have removed the use of `with` from our scripts a bit back, however after your report we have found that there are still few uses of the same in the framework we use - [BetaJS](https://betajs.com/).
> 
> We are looking to sort this out so that there are no errors raised due to same.

Amazing, thank you so much for the quick response 🙇

**Comment by gtsdeeto** [comment]
Hello, I'm facing similar issue 'With statements cannot be used with the "esm" output format due to strict mode', was there any update about this issue?

Thanks

**Comment by Bane-D** [comment]
Hi to both, unfortunately there is no update yet related to this.

**Comment by nyholmniklas** [comment]
I'm having the same issue, any updates or workarounds for this?

**Comment by Bane-D** [comment]
Hey Niklas,

No update as of yet. The BetaJS framework that we use is however open source and the issue with the `with()` calls should be specific to it only at this time as references in Ziggeo code have been replaced by proper codes.

Unfortunately I do not see any ETA assigned to it at this time.
