### ISSUE TITLE
Components not working if app is already using babel-polyfill.

### ISSUE THREAD

**Issue by jerrymao15** [Ziggeo/react-ziggeo#22]
Hi all,

I'm trying to use the `ZiggeoRecorder` component in my app, and it seems like it doesn't play well if `babel-polyfill` is already being imported. When using Webpack's dev server, my bundle fails to compile and I get this error:

```
Error: only one instance of babel-polyfill is allowed
```

I've also tried taking out my own `babel-polyfill` import, and I still get the error (maybe another library is also using it?)

**Comment by sambua** [comment]
Hi @jerrymao15 

Thanks for the info, please could you check [this link](https://github.com/babel/babel-loader/issues/401) and try to solve on the way they do? 

On the next release will try to prevent this error. So there will be no conflicts in the future. And will update status here.

Thanks and regards,
Rashad

**Comment by sambua** [comment]
#28
