### ISSUE TITLE
Error in FireFox 62.0.3 (64-bit)

### ISSUE THREAD

**Issue by Romanior** [Ziggeo/react-ziggeo#29]
Hello, I have error on loading player, with is weird b/c it should be fixed.

`TypeError: Argument 1 is not valid for any of the 1-argument overloads of URL.createObjectURL.`
 "react-ziggeo": "3.1.0",

Related https://github.com/Ziggeo/ziggeo-client-sdk/issues/17

**Comment by sambua** [comment]
Hello @Romanior ,

Thank you very much for the information. Please upgrade to `react-ziggeo: 3.2.0`.
