### ISSUE TITLE
Unknown prop `allowscreen` on <div> tag. 

### ISSUE THREAD

**Issue by WizOzHeir** [Ziggeo/react-ziggeo#35]
I have an issue with implementing screen record using Ziggeo. I add 'allowscreen' property to ZiggeoRecorder component but I got the following warning and screen recording not work.

**Comment by sambua** [comment]
Hello @Viscontes Anastasiia,

Could you please advice how you trying to check it?  Just wonder how div element is related.

Adding `allowscreen={true}` attribute to `ZiggeoRecorder` Component should be enough.

Also, you can check it in FireFox, for chrome and opera you need an additional extension. For localhost, you can use Ziggeo extension. But on your own domain, you have to generate personal extension. Here you can find detail tutorial on how you can easily generate a new one (https://ziggeo.com/features/screen-recording). After you can add extension IDs as shown here https://github.com/Ziggeo/react-ziggeo#recorder-option-screen-recorder

Thanks.
