### ISSUE TITLE
Full screen doesn't work on Android

### ISSUE THREAD

**Issue by novicaeton** [Ziggeo/react-ziggeo#37]
I integrated react-ziggeo (3.3.0 version) to the project I am working on. It's integrated to be used when creating feed entries. 

We have a problem with a player. When I record or upload a video using ziggeo, and try to view that video in full screen on Android, I see that video continues to run (I hear the sound) but I don't see any picture. Also, all the functions are lost (I am not able to click anything, nor to return to normal view).

It is only happening on full screen and on Android for recorded or uploaded videos (not for embedded). If I don't use full screen, everything is normal.

This is how we integrated it:

<ZiggeoPlayer
                    id={this.props.ziggeo}
                    apiKey={ZIGGEO_KEY}
                    video={this.props.ziggeo}
                    width={'100%'}
                    height={'100%'}
                    theme={'minimalist'}
                    themecolor={'minimalist'}
                    preventReRenderOnUpdate={false}
                    onAttached={this.handleAttached}
                    onRef={ref => (this.child = ref)}
                    onError={this.handleError}
                    style={styleVideo}
                />

Thanks in advance!

**Comment by sambua** [comment]
Hello @novicaeton ,

Thanks a lot that inform us. We have some changes related fullscreen bugs, will be applied on next release. We will test this case also and try to fix it soon.

Thanks!

**Comment by sambua** [comment]
Should be fixed with the latest commits
