### ISSUE TITLE
Setting volume on the video player is a pain, unless i'm mistaken.

### ISSUE THREAD

**Issue by ljsikuade** [Ziggeo/react-ziggeo#40]
Hi, I'm having difficulty understanding how my solution works exactly, but it does and I haven't found a better way. 

Currently I'm setting a ref on the player instance and then calling: 

`this.player.set_volume()
     this.player.playerInstance().set_volume(DEFAULT_VOLUME)`

Simply calling playerInstance().set_volume() doesn't work, as I thought it would intuitively. Also the documentation says that set_volume() takes a value between 1-100. But I've found that any number larger than zero causes full volume. 

What am I doing wrong?

**Comment by sambua** [comment]
Hello @ljsikuade ,

Sorry, our fault, the volume level is changing between `0.00 - 1.00`, changes will be made accordingly.

Thanks found it.

**Comment by sambua** [comment]
Documentation updated accordingly
