### ISSUE TITLE
Rerecording doesn't work

### ISSUE THREAD

**Issue by alexkim205** [Ziggeo/react-ziggeo#42]
Whenever I try to rerecord a video with the setup below, I get a `Cannot read property tagName of null` error and the recorder hangs. What can I do to fix this issue?

![Screen Shot 2019-04-01 at 12 46 08 AM](https://user-images.githubusercontent.com/13460330/55304088-bf2eb100-5417-11e9-8928-5b8288efa29b.png)

```javascript
<ZiggeoRecorder
              onRef={ref => (this.child = ref)}
              apiKey={API}
              // video={'ABCDE12345'}
              theme={'space'}
              themecolor={'blue'}
              width={'100%'}
              height={690}
              timeminlimit={0}
              timemaxlimit={240}
              enforce-duration={true}
              // responsive={true}
              // early-rerecord={true}
              // faceoutline={true}
              skipinitial={true}
              // skipinitialonrerecord={true}
              snapshotmax={0}
              picksnapshots={false}
              gallerysnapshots={0}
              localplayback={true}
              // onCountdown={this.tick}
              // onRerecord={this.onRerecord}
          />
```

**Comment by alexkim205** [comment]
bump

**Comment by sambua** [comment]
Hello @alexkim205 , sorry for late response, we're checking it, will back as soon as possible

**Comment by sambua** [comment]
Hello Alex, we have tested it with all options you've provided. It works as expected. 

Do you have any custom scripts or other 3rd party library like jquery or another js library?

If you can't provide it, please if possible just test without additional libraries to be sure that it works as a single library.

Thanks in advance

**Comment by sambua** [comment]
Hello Alex,

Could you please advice if you could fix an issue? If everything is solved I'll close this issue. If not please advice with more details so we could somehow help.

Thanks in advance.
