### ISSUE TITLE
Build size

### ISSUE THREAD

**Issue by rouvenherzog** [Ziggeo/react-ziggeo#44]
Hey everyone,

The minified build file currently has a size of 2.18 MB. In my opinion that's a bit chunky for production use. Any chance to reduce that size a bit?

Best

**Comment by sambua** [comment]
Hello Rouven, 

Most of the size is Ziggeo JS SDK which do a lot of job with useful features. Unfortunately for now it's not configurable to select feature you only used so generate SDK based on that. But if in the future there will be such options we will inform all our valuable users 🙂

**Comment by sambua** [comment]
Hello again Rouven. We will upgrade generation of the React SDK, where you will be able to exclude some themes which will decrease space. Will update soon how you can proceed 🙂 .

**Comment by sambua** [comment]
Hello again Rouven, 

Here's steps how you can achieve it. It will reduce about 300-350kb space but you'll be able use only default theme. Steps are below:

1. Clone this repo, `npm install` it.
2. Clone https://github.com/Ziggeo/ziggeo-client-sdk demo in separate folder. Run `npm install`. Open Gruntfile.js and remove these lines: https://github.com/Ziggeo/ziggeo-client-sdk/blob/master/Gruntfile.js#L61-L108 , after run `grunt` command.
3. Copy new generated build folder inside separate `ziggeo-client-sdk` folder to the `react-ziggeo/node_modules/ziggeo-client-sdk/` folder.
4. Run `npm run build` in the `react-ziggeo` root folder. Now you can integrate scripts inside `react-ziggeo/build` folder in you own project's `your_project_folder/node_modules/react-ziggeo`

Please let us know if you'll have any difficulty with this process.

**Comment by rouvenherzog** [comment]
Hey @sambua! Thank you for the detailed description! It's much appreciated.
A third party lib of 1.5MB is still too big to be delivered as a dependency of our app. We'll have to add lazy loading to our setup in order to incorporate the ziggeo player, which can definitely be a make-or-break decision in terms of using ziggeo at all since it adds a considerable complexity overhead architectural wise.

I can only urge you to work on the file size of the ziggeo sdk.

Best

**Comment by fractalgelfo** [comment]
Bump on this. Ziggeo is literally the majority of my bundle size and causing the web app to load slowly.

@rouvenherzog  did you end up implementing lazy load? How did that go for you and want to share any approaches that worked or didn't?

**Comment by Bane-D** [comment]
Hi there,

Our service is designed to make it easy to grab and use and offer the same to people that do not want to or do not have someone to or want to go into code. This makes the file include things like languages, the themes (both JS codes and CSS codes for them) however it also includes auth system, etc. what you might not use.

If you are looking to optimize we have the SDK variation that you can get here: https://github.com/Ziggeo/ziggeo-client-sdk.

This SDK can be optimized to exclude the things you do not want and then compile it yourself. Using that you could create a file that you can then use within the React or other SDKs loading our system.

Other than that, you can reduce the codes using the [steps mentioned by my colleague above](https://github.com/Ziggeo/react-ziggeo/issues/44#issuecomment-516533209).

Lazy load would of course also help to delay when the files are loaded.

Regards,
Bane

**Comment by fractalgelfo** [comment]
cool, i will look into using that SDK variation!

**Comment by sambua** [comment]
Hello @fractalmarc,

Above [message](https://github.com/Ziggeo/react-ziggeo/issues/44#issuecomment-516533209) already outdated. We made changes now you can just set `CustomCompileOptions` options from here: https://github.com/Ziggeo/ziggeo-client-sdk/blob/master/Gruntfile.js#L11 and run grunt command. 

You can remove themes and locales, especially locales took a lot of size, just set `locales: ['en']` or other locale you want to use.
