### ISSUE TITLE
Multiple upload

### ISSUE THREAD

**Issue by novicaeton** [Ziggeo/react-ziggeo#46]
Is it possible to enable uploading multiple videos at one go?
We integrated Ziggeo to feed posts, and the client asked us to enable that, but I haven't found anything about that in your documentation. 
Thanks.

**Comment by sambua** [comment]
Hello @novicaeton ,

You can create custom upload form, and hadle it from the server side using of our server side SDKs. It depends language your's using in server side ( PHP, Node, Ruby etc. )

Here's example via NodeJS https://github.com/Ziggeo/ZiggeoNodeSdk/blob/master/demos/video_upload_multiple.js

**Comment by novicaeton** [comment]
Hello sambua,

I am using only react-ziggeo and all the events in React. So I almost don't use ziggeo at all on the server side with the current architecture (except for saving them in PHP). 

I saw in the documentation of ziggeo parameter that there is a playlist as an option. Can I pass more videos in that playlist and save them in PHP?

**Comment by sambua** [comment]
@novicaeton ,

Correct there'a an option playlist where you can pass several video tokens and play them one by one. 

In your case, you can upload vides in backend via AJAX form, and store video tokens as soon as you get them, and send back to the frontend video tokens comma separated as a player's playlist option.

P.S. it's in our list of todos to add multi-upload option from frontend directly.

If still has questions or need more clarification will be glad to support.
Thanks
