### ISSUE TITLE
Setting up and using audioonly on uploader

### ISSUE THREAD

**Issue by smdowl** [Ziggeo/react-ziggeo#50]
I can get the audio uploader working with the standard js library, but it then confilcts with this one when I try to use it

**Comment by smdowl** [comment]
Have realised that there seems to be an issue using that flag anywhere in the react project. not sure if i'm just not understanding how to use it properly.

**Comment by sambua** [comment]
Hello,

Could you please send code example how you implement it? So we be able to reproduce it.

thanks

**Comment by Bane-D** [comment]
Hi Shaun,

Hope you do not mind me adding to what my colleague already asked. Your title mentioned `audioonly` so I left it in the title, however wanted to check if you might be thinking of `onlyaudio` parameter?

Also if you are, can you please let us know if I understood you correctly that you are looking to limit the file uploads to only allow audio files such as `some_song.mp3` or `some_song.wav` etc.

Regards,
Bane

**Comment by smdowl** [comment]
sorry, moronic support request on my side. was banging my head against this (probably my fault entirely) and have moved over to a different service at this point. 

Next time I make a request I'll be sure to include more details so it's not a complete waste of time. my apologies!
