### ISSUE TITLE
How to style ziggeo colors / icons  ?

### ISSUE THREAD

**Issue by bymoe** [Ziggeo/react-ziggeo#55]
I am trying to add my own icons and change some text, For example If I want to add a font awesome icon instead of the text "Record"

**Comment by sambua** [comment]
Hello @ImSolitude 

Unfortunately there's no way to change icons or color programmatically as all CSS are pre-generated. You can inject it with selectors, we are not often change CSS selectors. You can change icons with renaming classes to font-awesome class names, and colors just add custom CSS with replacing our styles.
