### ISSUE TITLE
How to obtain access to recorder instances and methods using React Hooks?

### ISSUE THREAD

**Issue by bymoe** [Ziggeo/react-ziggeo#56]
I am using Hooks with Ziggeo,
According to documentation to use instances and methods I should do this:
```
<ZiggeoRecorder
        apiKey={apiToken}
        onRef={ref => (setChild(ref))}
/>
```
So this `child` suppose to be a state ? `const [child, setChild] = useState();` ?
Because when I do this `child` is always undefined.

![code](https://user-images.githubusercontent.com/20565199/81467524-cc54cc80-91e1-11ea-867d-03b71fa2265b.png)

The Goal here I want to start recording once Ziggeo attached, So After the "Start Recording" immediately not when the User click on the record text on the bottom bar.

**Update**: When I try to `console.log(ref)` It actually logs the data but for some reason my state still `undefined` 

![code](https://user-images.githubusercontent.com/20565199/81467640-bc89b800-91e2-11ea-9e86-daddfbdd16e2.png)

**Comment by sambua** [comment]
Hello @ImSolitude ,

you can achieve it with useEffect

```
const [recorder, setRecorder] = useState(null);

useEffect(() => {
      if (recorder) {
          recorder.record();
      }
}, [recorder]);

<ZiggeoRecorder
    onRef={e => setRecorder(e)}
/>

```

**Comment by bymoe** [comment]
Thank you @sambua,

What I am trying to achieve is to record when the Hit this button, 
![error](https://user-images.githubusercontent.com/20565199/81487870-93146f00-926a-11ea-9e8a-77aba093c6c7.png)

**Comment by sambua** [comment]
you'r welcome @ImSolitude , you can append button when recored is available. Or can set it as disabled and as soon as get recorder inside useEffect set button clickable. As it took short time while recorder becomes ready to use.

**Comment by ImSolitude** [comment]
Thank you, But this is still a workaround and not a good one, not sure why this is closed, It can be easily solved If I can get the recorder instances and methods using Hooks.

**Comment by bymoe** [comment]
Thank you, but not sure why this is closed. I still cannot get to `.record()` `.rerecord()`, etc... outside the `useEffect`. This is still my problem. I understand that I cannot get the `ref` of something isn't there yet, but can I choose to mount Ziggeo when the component mount not when I click that button?

**Comment by sambua** [comment]
hello @ImSolitude , sorry, as you didn't reply thought it fix your issue. Will reply soon with possible fixes

**Comment by sambua** [comment]
Here's example how recorder could be access outside of the useEffect; 

```js
    const [recorder, setRecorder] = useState(null);
    const [updateInstance, setUpdateInstance] = useState(false);
    useEffect(() => {
        if (recorder) {
          setUpdateInstance(false);
       }
    }, [recorder]);

    const handleStartRecorder = () => {
        if (recorder) {
            recorder.record();
        }
    }
    
    const handleStopRecorder = () => {
        if (recorder) {
            recorder.stop();
        }
    }



    // !!! In case, changing initial settings and DOM view changes, it should re-render and get a new Recorder instance
   const handleChangeTheme = () => {
        if (recorder) {
          setUpdateInstance(true);
          recorder.set("theme", "cube");
          setRecorder(recorder);
        }
   }


 return(<>
             <div>
                <button onClick={handleStartRecorder}>Record</button>
                <button onClick={handleStopRecorder}>Stop</button>
                <button onClick={handleChangeTheme}>Set Theme Green and Cube</button>
            </div>
             
            <ZiggeoRecorder
                apiKey={API_KEY}
                updateInstance={updateInstance}
                onRef={e => setRecorder(e)}
           />
```
