### ISSUE TITLE
Error calling method on NPObject when trying to record video on Safari 

### ISSUE THREAD

**Issue by jmknoll** [Ziggeo/react-ziggeo#57]
When I try to record a video, the demo project throws an Error on Safari
Error text: Error calling method on NPObject.

This happens after pressing record, and occurs in both the demo project and my live project.

Environment:  
* OS: (Desktop) MacOS 10.15.3 Catalina
* Browser: Safari 13.0.5

Image attached

<img width="1236" alt="Screen Shot 2020-05-10 at 1 01 23 PM" src="https://user-images.githubusercontent.com/1687908/81505622-a3eed000-92be-11ea-841a-bf24dc41c7a0.png">

**Comment by sambua** [comment]
Hello, seems it's related to Flash Player in Safari. Could you please add webrtc_streaming settings to the recorder ?

```
 webrtc_streaming_if_necessary={true}
```

**Comment by sambua** [comment]
Please use only ` webrtc_streaming_if_necessary={true}` only as it will replace flash in Safari

**Comment by jmknoll** [comment]
Thanks @sambua that seems to fix this issue. Maybe I missed it, but are you able to add this info to the ReactZiggeo docs to prevent this issue for other developers in the future?

**Comment by sambua** [comment]
Thank you for the advice @jmknoll , will be added. Only in normal condition it should be work with flash player. Seems it is  recent bug raised with new Safari version.
