### ISSUE TITLE
Ziggeo Player doesn't re-render on update

### ISSUE THREAD

**Issue by jmknoll** [Ziggeo/react-ziggeo#58]
preventReRenderOnUpdate={false} props doesn't force component to re-render when passed a new value for the video prop.

**Comment by sambua** [comment]
This feature seems turned off after switched to hooks, as hooks don't has re-render whole component like it was done before, where for one class had only one lifecycle methods. Now is best way re-render whole component by setting some state. Could you please advice situation how you plan to implement it? Will try help to find a solution.

**Comment by jmknoll** [comment]
Thanks @sambua.  I want to record a video, then upload it, navigate to a new page, and record another video. Currently, I see the same instance of the recorder on the second page, and can only create a new recorder instance by unmounting and remounting the recorder component. Please let me know if there is a better way of doing this.

**Comment by MichaelLonin** [comment]
The same situation on my side. I want to control `theme` and `themeColor` from UI and I use Recorder/Player to show preview.

**Comment by jmknoll** [comment]
@sambua Given React's rendering model, a component should update when its props are updated. Requiring the developer to manually mount/unmount the video player is a significant break from this model, and makes the product challenging to use in any non-trivial use case. I highly recommend fixing this.

**Comment by Bane-D** [comment]
Hi to both,

Michael some properties are made to be possible to just turn them on and off, however most are not. They require you to recreate the embedding (like player or recorder) instead. If your goal is to do this on the embedding as is (without recreation of the same) then this would look like it is the same issue however is a bit separate from what is happening and not possible. However if you mean to add something and component is automatically re-created for you, then this is right issue. I am saying this just to avoid confusion down the road :)

Jameson my colleague is looking into this. Will try to get some more details about it. In general our goal is to implement things in a way that best matches the experience that would usually be expected - in this case in our React SDK.

**Comment by sambua** [comment]
Hello @jmknoll , please could you try latest release ( Documentation with example https://github.com/Ziggeo/react-ziggeo#trigger-instance-update )

**Comment by sambua** [comment]
Hello @MichaelLonin , regarding your request. Ziggeo is build on `BetaJS` library which is also includes re-render options when one ore more attributes are changes. So you can achieve your goal with changing `themecolor` in 2 ways:

1. Recently added `updateInstance` React way: 

```
const [recorder, setRecorder] = useState(null);
const [themeColor, setThemeColor] = useState('default');
const [updateInstance, setUpdateInstance] = useState(false);

 const handleChangeThemeColor = () => {
        if (recorder) {
            setThemeColor('red');
            setUpdateInstance(true);
        }
    }

<ZiggeoRecorder
    ...
    themecolor={themeColor}
    updateInstance={updateInstance}
    onRef={e => setRecorder(e)}
    ...
```

2. With Ziggeo/BetaJS built in setter and getters:

```
    const handleChangeThemeColor = () => {
        if (recorder) {
          if (recorder.get("themecolor") === "red")
              recorder.set("themecolor", "blue");
          else
              recorder.set("themecolor", "red");
        }
    }

```

**Comment by MichaelLonin** [comment]
@sambua I have got a chance to try your solution and I got other issue there, our UI should be able to modify instance multiple times:
<img width="775" alt="Screenshot 2020-06-17 at 20 04 44" src="https://user-images.githubusercontent.com/14862640/84927767-f7cab100-b0d5-11ea-8391-6a481f7654ea.png">
so `updateInstance` boolean variable can't do it properly, let's say I can try to add some timeout and switch it back to null but I don't think this is a good idea, I believe `ZiggeoPlayer` or `ZiggeoRecorder` should handle it automatically under the hood according to React reactive data flow. Please reopen the issue.

**Comment by sambua** [comment]
Hello @MichaelLonin , It's not correct to use with SetTimeOut, as soon as you got a new instance you have to use `updateInstance` as false. Like you do when load some data from server, You set isLoading to true, and if got all data set isLoading to false. You have to use useEffect listening recorder changes and set `updateInstance` to false. Please look to [documentation example](https://github.com/Ziggeo/react-ziggeo#trigger-instance-update)

**Comment by sambua** [comment]
Also, @MichaelLonin why you are not using build in setter? I will be more effective than each time rebuild instance of the recorder. You can set almost all settings, like `recorder.set("attribute_name", "any_aceptable_value");`

**Comment by MichaelLonin** [comment]
Hello @sambua! First of all thanks for your extra fast response and support :) 
1) We are talking about React App.
> It's not correct to use with SetTimeOut, as soon as you got a new instance you have to use updateInstance as false

Of course I don't want to do it was just bad example.

2) My code, the same for `ZiggeoRecorder`

```
const VideoPlayer: React.FC<Props> = ({
  token = null,
  videoSettings = defaultVideoSettings,
  className = '',
  onEnded
}) => (
  <ZiggeoPlayer
    apiKey={process.env.REACT_APP_ZIGGEO_API_KEY}
    source={!token ? crowdyVideo : undefined}
    video={token || ''}
    width="100%"
    height="100%"
    theme={videoSettings.theme}
    themecolor={videoSettings.themeColor}
    skipinitial={videoSettings.playerSettings.skipInitial}
    className={className}
    onEnded={onEnded}
  />
);

export default VideoPlayer;
```
So as you can see it is functional component controlled by props only. As far as I understand your solution I should do something like this:

```
React.useEffect(() => {
     setUpdateInstance(true);
}, [videoSettings.theme])
```
but it can help only once.

> recorder.set("attribute_name", "any_aceptable_value");

We are using React so maybe I can React.Ref to Ziggeo instance and use it with set method, but anyway it will produce a lot of code and React don't like direct DOM manipulations.
I believe ZiggeoPlayer or ZiggeoRecorder should handle it automatically under the hood according to React reactive data flow. What do you think?

**Comment by sambua** [comment]
Hello @MichaelLonin ,

Sorry missed your message. Here's example how you can handle themeColor, if you're using own component an through props:

```
const VideoPlayer = (props) => {
  const { apiKey, themeColor, video } = props;

  const [player, setPlayer] = useState(null);
  const [updateInstance, setUpdateInstance] = useState(false);

  useEffect(() => {
    if (player) setUpdateInstance(false);
  }, [player]);
  
  useEffect(() => {
    setUpdateInstance(true);
  }, [themeColor])

  return(<ZiggeoPlayer
    theme={"cube"}
    apiKey={apiKey}
    themecolor={themeColor}
    video={video}
    onRef={ref => {return (setPlayer(ref))}}
    updateInstance={updateInstance}
  />);
};
```

In your parent component:

```
const ParentVideoPlayer = () => {
  const [themeColor, setThemeColor] = useState('red');

  const toggleThemeColor = () => {
    if (themeColor === "red")
      setThemeColor("blue");
    else
      setThemeColor("red");
  }

  return (
    <div>
      <PlayerComponent
        apiKey={API_KEY} video={VIDEO_TOKEN} themeColor={themeColor}
      />
      <button onClick={toggleThemeColor}> Toggle Theme Color </button>
      </div>
    );
}
```

If you have any additional questions please don't hesitate to ask.

**Comment by MichaelLonin** [comment]
@sambua Thanks for the example, not obvious but works :)

**Comment by sambua** [comment]
You're welcome @MichaelLonin :)
