### ISSUE TITLE
noaudio prop disables video upload on Firefox

### ISSUE THREAD

**Issue by jmknoll** [Ziggeo/react-ziggeo#59]
If I set noaudio={true}, I am unable to upload videos. The onUploading event never fires, and the video is not uploaded to the server.

OS: MacOS 10.15.3 Catalina
Browser: Firefox 75

**Comment by albin-engstrom** [comment]
Does it work with 3.4.0 for you?

I'm having a likely related issue where the noaudio prop doesn't work with versions above that one. I've been trying to use the recorder for recording the screen, and when that prop is set to true it still tries to access the microphone and if I don't let the browser allow that things break.

If I downgrade to version 3.4.0 it works like it should and microphone access is not asked for.

**Comment by sambua** [comment]
hello @jmknoll really it's not working correctly with `noaudio` and FireFox with react SDK. We will try to fix it shortly.

hell @albin-engstrom this bug will be also fixed soon

thank you for informing about these bugs

**Comment by sambua** [comment]
Hello, these bugs were, fixed with the latest release of Ziggeo JS SDK, you can apply just by upgrading `ziggeo-js-sdk` package, or please wait little bit will be applied during this week.

**Comment by sambua** [comment]
Package was upgraded to `Version 4.1.0` no-audio related bug should be fixed. 

Thanks.

**Comment by sambua** [comment]
Was fixed with #62
