### ISSUE TITLE
componentWillReceiveProps event, reset player

### ISSUE THREAD

**Issue by milosmoto** [Ziggeo/react-ziggeo#6]
Can you extend reseting ZiggeoPlayer component when props ziggeo-video is updated.

So I have integration like this:
```
import { ZiggeoPlayer } from 'react-ziggeo';
render(){
    return (
                <ZiggeoPlayer
                    apiKey={APPPLICATION_TOKEN}
                    ziggeo-video={this.props.ziggeo_token}
                    />
    )
}

```
So what I want is when "this.props.ziggeo_token" is updated that ziggeo reset my ZiggeoPlayer?

**Comment by sambua** [comment]
Sure, will look for the possibility of the task in the next release. Thanks for the suggestion.

**Comment by sambua** [comment]
Hello @milosmoto , after upgrading to 1.3 you can change video dynamically with `ZiggeoEmbedPlayer` component, here I've add some short instruction: [Instruction how to change video](https://github.com/Ziggeo/react-ziggeo/tree/master/demo) . You have to make `setState` change to be able to rebuild UI.

**Comment by sambua** [comment]
Hello @milosmoto , after upgrading to `v1.3.0` you can change video dynamically with `ZiggeoEmbedPlayer` component, here I've add some short instruction: [Instruction how to change video](https://github.com/Ziggeo/react-ziggeo/tree/master/demo) . You have to make `setState` change to be able to rebuild UI.

**Comment by milosmoto** [comment]
@sambua  Well done!! Thanks!

Can you check one more thing, it happens after upgrade on v1.3.0

TypeError: invalid 'in' operand this.__extendables

If you can't reproduce tell me I can help you with more details. Thanks

Inside:
ziggeo-js-sdk - v0.0.29 - 2017-11-03
Copyright (c) Ziggeo
Closed Source Software License.
*/

**Comment by sambua** [comment]
Hi @milosmoto thanks for feedback again 🙂 

Yes, could you please provide with settings you apply and in which browser/mobile.

Thanks in advance

**Comment by milosmoto** [comment]
@sambua Sorry for delayed answer.

It happens on every page where ZiggeoEmbedPlayer is imported.

Error in FF is like this:
TypeError: invalid 'in' operand this.__extendables

In Chrome is something like this:

TypeError: Cannot use 'in' operator to search for 'application_status' in undefined

Configuration:
```
import { ZiggeoEmbedPlayer } from 'react-ziggeo';

<ZiggeoEmbedPlayer
                    id={this.props.ziggeo_token}
                    apiKey={APPPLICATION_TOKEN}
                    video={this.props.ziggeo_token}
                    width={320}
                    height={240}
                    theme={'minimalist'}
                    themecolor={'minimalist'}
                />
```

**Comment by sambua** [comment]
Hi @milosmoto, 

Thanks for detail info, will check and revert to you. Btw we have launched 2nd version. For now if possible you can try the newest version where with your settings just need replace `ZiggeoEmbedPlayer` with `ZiggeoPlayer`.

**Comment by milosmoto** [comment]
@sambua @Bane-D 
Didn't solve my problem, because when I revert on ZiggeoPlayer, refresh player doesn't work anymore.

Problem from this thread, first 2 messages, where you suggested to move on ZiggeoEmbedPlayer, that doesn't work with ZiggeoPlayer?

**Comment by sambua** [comment]
Hi @milosmoto , sorry for late reply. 

Could you please check latest version 2.1.1 it should solve most above message? It's achieved by stopping re-render automatically on an update which fires on state change.

In case if you want to re-render during state change which not preferable to use in the first render inside `componentDidMount`, you can use new added option `preventReRenderOnUpdate={boolean}`.

One more kindly note, starting from version 2.0 there're no `ZiggeoEmbedPlayer` it was replaced via `ZiggeoPlayer` where props are declared like it was in `ZiggeoEmbedPlayer` w/o `ziggeo-` prefix.

If any issue or questions please let me know.

Thanks

**Comment by milosmoto** [comment]
@sambua 

I am on version 2.1.2, but I have previous problem still:
Here is how you can reproduce this:

```
<ZiggeoPlayer
                    id={this.props.ziggeo_token}
                    apiKey={APPPLICATION_TOKEN}
                    video={this.props.ziggeo_token}
                    width={'100%'}
                    height={'100%'}
                    theme={'minimalist'}
                    themecolor={'minimalist'}
                    preventReRenderOnUpdate={false}
                />
```
Basically very important feature for me is automatic refresh player on props changed(state). That's why I set preventReRenderOnUpdate={false}.

If last parameter is on true, there is no error.

Can you fix just this error?

**Comment by sambua** [comment]
Hi @milosmoto 

- Are you try to use `setState` inside componentDidMount?
- Also, could you please advice scenario? Maybe I can provide an alternative solution?

I'm working on solving this issue also, as soon as there will be any updates for this special case, I'll let you know.

Thanks

**Comment by milosmoto** [comment]
Hi @sambua,

I have solution for this, unmount than mount component again will reload player with new token. So it's not that urgent, it will be nice to have it solved.
Here is full component that is using ZiggeoPlayer:
```

import React from 'react';
import { ZiggeoPlayer } from 'react-ziggeo';
import { APPPLICATION_TOKEN } from './constants';

class Player extends React.Component {
    constructor(){
        super();
        this.state = {
            show: true
        };
    }
    componentWillReceiveProps(nextProps){
        //Temporary hack until ziggeo fix problem with
        //preventReRenderOnUpdate
        if(this.props.ziggeo_token !== nextProps.ziggeo_token){
            this.setState({show:false});
            setTimeout(function(){
                this.setState({show:true});
            }.bind(this),500);
        }
    }
    render () {
        if(!this.state.show){
            return null;
        }
        if(this.props.ziggeo_token){
            return (
                <ZiggeoPlayer
                    id={this.props.ziggeo_token}
                    apiKey={APPPLICATION_TOKEN}
                    video={this.props.ziggeo_token}
                    width={'100%'}
                    height={'100%'}
                    theme={'minimalist'}
                    themecolor={'minimalist'}
                    preventReRenderOnUpdate={true}
                />
            );
        }else{
            return null;
        }
    }
}

export default Player;
```
As you can see in componentWillReceiveProps is that fix for unmount and than mount again.
