### ISSUE TITLE
How to make recorder responsive?

### ISSUE THREAD

**Issue by zamirkhan** [Ziggeo/react-ziggeo#60]
My recorder code looks like this: 

```
        <ZiggeoRecorder
          apiKey={config[config.STAGE].ziggeo.API_KEY}
          responsive={true}
          onRecording={this.recorderRecording}
          onUploading={this.recorderUploading}
        />
        <link
          rel="stylesheet"
          href="https://assets.ziggeo.com/v2-stable/ziggeo.css"
        />
```

However, the recorder still wants to take up a 640x480 space. I would like it to be responsive to its container.

**Comment by zamirkhan** [comment]
When I inspect the element tree, the `video-recorder-container` has its `style.width` and `style.height` explicitly set to 640x480.

**Comment by sambua** [comment]
Hello @zamirkhan You can set width 100% and any height. Actually 640x480 is streaming of the recorder it's set by default if not setting recordingwidth/height.

**Comment by zamirkhan** [comment]
Thank you, that seems to have worked.

**Comment by sambua** [comment]
you'r welcome :)

**Comment by zamirkhan** [comment]
I still haven't got this quite working. While the initial recorder fits within the allotted space, when I upload a video with a different aspect ratio (e.g. portrait), then that video is displayed expanding into the full width of its container and thus its height is much greater than its container and it is cropped. I would expect it to resize itself to fit within the container, no? Or at least show a letter-boxed display of the video?

With the video displayed, it does not obey the `height` or `max-height` setting of its container.

It seems that both the recorder (e.g. with active webcam) and video player (to show the recorded/uploaded video afterward) want to fill the available width first, and then determine their height, but this is not truly responsive.

Can you provide an example where the recorder always fits within its parent, regardless of aspect ratio, without hard-coding any sizing on the recorder itself?

**Comment by sambua** [comment]
If it's inside some other element, and want to fit that parent element could you try `stretch` ?

**Comment by zamirkhan** [comment]
So adding a `stretch` prop to the `<ZiggeoRecorder />`? I tried both  `<ZiggeoRecorder stretch />` and `<ZiggeoRecorder stretch={true} />` and neither seem to change the behavior. Does it need to be combined with other attributes, like `responsive`, `height`, or `width`?

**Comment by zamirkhan** [comment]
Should this issue be re-opened? I'm still unable to get the recorder to fit reliably inside its container throughout the entire video submissions process.

**Comment by sambua** [comment]
hello, @zamirkhan could you please, share code, and what device you use? Will try to recreate it. There's also stretchheight which has to fit to height and should calculate height.

**Comment by zamirkhan** [comment]
Here is my code. Please let me know what I should do such that the recorder will fit within it's parent container, no matter what the size of that container. Currently the container has a maximum size of 640x360, but could be smaller, for example if it is being viewed on a phone. I'm simply testing this on my Macbook Pro in Chrome and then using the Device Toolbar to test out different viewport scenarios.

```
      <div
        className="my-2 mx-auto recorder-rounded"
        style={{
          maxWidth: "640px",
          maxHeight: "360px",
        }}
      >
        <ZiggeoRecorder
          apiKey={config[config.STAGE].ziggeo.API_KEY}
          stretch={true}
          theme="elevate"
          onRecording={this.recorderRecording}
          onUploading={this.recorderUploading}
          picksnapshots={false}
          sharevideo={[]}
          allowcustomupload={false}
          rerecordableifexists={false}
        />
        <link
          rel="stylesheet"
          href="https://assets.ziggeo.com/v2-stable/ziggeo.css"
        />
      </div>
```

**Comment by zamirkhan** [comment]
Also, using `stretchheight` or `stretchwidth` just seemed to distort the aspect ratio. I'd like the recorder to maintain its desired aspect ratio and also fit within the parent container.

**Comment by zamirkhan** [comment]
I've gotten a little bit further, however, this problem scenario still remains:

1. Use recorder on desktop view, it has a size of 640x360 and uses `stretchheight`, for example.
2. Using Upload function, upload a video with portrait aspect ratio
3. When the upload is complete and verified, it shows a poster image of the video, but the poster image width is the full width of the player, and thus its height is far greater than the height of the player.
4. When the video is played, this is corrected, presumably due to `stretchheight`, but the problem in (3) remains unsolved.

<img width="663" alt="Screen Shot 2020-05-22 at 5 00 52 PM" src="https://user-images.githubusercontent.com/2654175/82709307-48bdc580-9c4e-11ea-92ea-fc1789cc10bb.png">

**Comment by zamirkhan** [comment]
Any thoughts on how to proceed to avoid this?

**Comment by Bane-D** [comment]
Hi Zamir,

Just jumping in here to check something. I believe based on what you said that you are only experiencing the issue with the image, not the video itself. Am I correct in this?

Regards,
Bane

**Comment by zamirkhan** [comment]
That's right. I haven't yet tested this thoroughly with a lot of videos, but in the scenario that I did test, the preview image for the player showed up as above, but when playing the video showed as expected. However, having the image show up that way would not be acceptable for our usage.

**Comment by Bane-D** [comment]
Ah OK, thought that to be case.

**Comment by Bane-D** [comment]
I reopened this for now and want to check in with you if you mind using CSS / some JS code to fix this. If it works right then my colleague can see how the same would be added into our standard scripts.

**Comment by zamirkhan** [comment]
I'd be willing to try. That said, I have moved onto some other development work and may not be able to try it out immediately. I have to say I'm a bit surprised because this seems like a fairly vanilla use-case to me. Is there something non-standard I'm doing?

**Comment by Bane-D** [comment]
That is fine, I will send it your way then when you have a chance to check it out perfect.

There is nothing wrong what you are doing, it is just that these CSS rules are quite a story in themselves sometimes. It is always a fine line between making something easy to restyle by others and to not be too easily restyled on some page by browser codes or other codes, yet so many different ways that can happen.

With all that said, and without seeing the actual page itself, can you try the following:
```html
<style>
.ba-videoplayer-stretch-height .ba-videoplayer-container img.ba-videoplayer-video {
    max-height: 100%;
    min-width: auto;
    width: auto;
    transform-box: border-box;
    transform: translateX(-50%);
    left: 50%;
}
</style>
```
* It is taking into account that you also specify the `stretchheight` parameter and to remove the `stretch` parameter for now.
* `stretch`, `stretchheight` and `stretchwidth` can not be set together rather only one for itself.

Regards,
Bane

**Comment by zamirkhan** [comment]
While this does fix the preview image issue, the overall recorder is still not really responsive. For example, if I view it on a mobile size screen, I see the following:

<img width="415" alt="Screen Shot 2020-06-11 at 2 52 29 PM" src="https://user-images.githubusercontent.com/2654175/84427722-58984c00-abf3-11ea-9730-1d8226369c6f.png">

Here is the relevant code (and I'm using the CSS you provided):

```
          <ZiggeoRecorder
            stretchheight={true}
            responsive={true}
            theme="cube"
          />
```
(there are more props on the element, but those are the ones relating to how it looks)

**Comment by Bane-D** [comment]
Awesome, glad to hear that the CSS code fixes the preview for you Zamir.

Now in terms of the recorder responsiveness can you please try using the following code instead:
```javascript
          <ZiggeoRecorder
            stretchheight={true}
            width="100%"
            theme="cube"
          />
```

Please do note that this would be as responsive as the placeholder element (parent element) that hosts it.

Regards,
Bane

**Comment by zamirkhan** [comment]
Thank you. Instead of `stretchheight`, would another responsive approach be to set both width and height to 100%?

**Comment by Bane-D** [comment]
I believe that you should be good with that code, however of course please let us know how it goes.

In theory it should be enough, however from experience i know that some CSS can cause some subtle difference for each website hence all the different parameters and we are always happy to help find the best one for you :)

**Comment by sambua** [comment]
In our new releases recorder was made more response friendly.
