### ISSUE TITLE
Support for custom localization strings?

### ISSUE THREAD

**Issue by jmknoll** [Ziggeo/react-ziggeo#61]
Your browser SDK supports custom localization strings, but its not clear how to implement this in the React SDK.

https://ziggeo.com/docs/sdks/javascript/browser-integration/localization

**Comment by sambua** [comment]
hello @jmknoll sorry for non-clear documentation, will be added soon. You can apply it simply using `locale` prop

For example: `locale={'de'}`

**Comment by jmknoll** [comment]
Thanks @sambua, but I was actually referring to the specification of custom strings, not just the specification of a locale. 

For example, `ZiggeoApi.V2.Locale.mediaLocale.register({"ba-videorecorder-chooser.record-video": "Rec"}, 10);`

**Comment by sambua** [comment]
Hello @jmknoll , 

New `mediaLocales` prop  added in `Version 4.1.0` .
https://github.com/Ziggeo/react-ziggeo#adding-localization 

Thanks.

**Comment by sambua** [comment]
Fixed with #62
