### ISSUE TITLE
Unknown prop ziggeo-onlyaudio

### ISSUE THREAD

**Issue by milosmoto** [Ziggeo/react-ziggeo#7]
"Warning: Unknown prop `ziggeo-onlyaudio` on <ziggeorecorder> tag. Remove this prop from the element.

It works but there is warning.

**Comment by sambua** [comment]
Hi, @milosmoto thanks for the issue report, will solve soon on next update.

**Comment by sambua** [comment]
By upgrading to `v 1.3.0` warning will be disappeared.
