### ISSUE TITLE
Error calling method on NPObject. (MacOS Safari)

### ISSUE THREAD

**Issue by MichaelLonin** [Ziggeo/react-ziggeo#70]
Safari: Version 13.1.2 (15609.3.5.1.3)
ZiggeoRecorder infinity loading and error in console: Error: Error calling method on NPObject.
<img width="916" alt="Screenshot 2020-07-29 at 20 18 08" src="https://user-images.githubusercontent.com/14862640/88831984-c830bd80-d1d8-11ea-9e69-cd18d6bf9d7f.png">

**Comment by Bane-D** [comment]
Hi Michael,

Based on the error you mentioned it looks like Adobe Flash was being loaded. Now I do see the "translate.google.com" to be mentioned in the top left corner, so just want to check if you tried translating the page where the recorder is added? Then did you on this translated page you see the error, or do you see the error when you go to the page directly?

Also, can you please let us know the recorder code you are using?

Regards,
Bane

**Comment by MichaelLonin** [comment]
Hi Bane! Thank you for quick response.

> Then did you on this translated page you see the error, or do you see the error when you go to the page directly?

"translate.google.com" just domain example, the same page works on chrome without any issues

recorder code:
<img width="995" alt="Screenshot 2020-08-01 at 18 50 52" src="https://user-images.githubusercontent.com/14862640/89105231-0d96fa00-d428-11ea-9809-d6b0ce14b004.png">

please let me know if you need some additional info. Thanks in advance!

**Comment by Bane-D** [comment]
Hi Michael,

Looking at the code like that it does not seem to have anything that really looks wrong. The only part I would suggest changing is the `undefined` part for video profile. In general we expect this to be string or not set at all.

Could you see what the code looks like once parsed? Same code just with the properties applied to see if any of them look wrong?

I would also try and removing the 3 event handlers you have set, just so that we can make sure it is none of them causing some error and down the road causing issue you experience.

Cheers,
Bane

**Comment by MichaelLonin** [comment]
Hi Bane!
Thanks for response.

> Looking at the code like that it does not seem to have anything that really looks wrong. The only part I would suggest changing is the undefined part for video profile. In general we expect this to be string or not set at all.

From JS perspective it is equal to undefined anyway :)

I have checked non localhost env. here: https://app.crowdy.ai/video-testimonials/survey/35d4c0ba-bda6-4319-b88a-a1aaa322881c/fa238d21-5cf3-4651-b6e6-0c4013a1303a/00000000-0000-0000-0000-000000000001 and looks like it works. There we are using `4.0.5` version instead `4.3.1` which we are using locally but `4.0.5` doesn't work locally either. So seems like localhost env. issue, once new production release will be deployed I will back to you. 

Thanks!

**Comment by MichaelLonin** [comment]
Validated on test env. works as expected, so localhost related issue, thanks for support, we can close issue now :)

**Comment by Bane-D** [comment]
Glad to hear that it is working for you now and that it is part of the test environment causing it.

In terms of suggestion for value, we can always change the default value of any parameter to for example empty string or "auto", null, etc. This is why I suggest always setting the value that you want to use and leaving all others unset as best practice ;)

Closing this issue then based on your feedback and as always do reach out if there is anything else we can help you with :)
