### ISSUE TITLE
Recorder.reset() results in 403 error

### ISSUE THREAD

**Issue by annaPerdomo** [Ziggeo/react-ziggeo#71]
Hello again! 

After upgrading to version 4.3.0 I ran into an issue with the function that resets the Ziggeo Recorder component. 

Within a React functional component, when trying to use recorder.reset(), the recorder will look like it's been reset and show the main record button again. After clicking on the record button, the countdown will start but after the countdown ends the recorder shows me a 403: forbidden error. Below is the code I'm using for the recorder as well a screenshot of the error. 

```
<VideoRecorder
  _key={videoKey}
  allowcustomupload={false}
  allowupload={false}
  apiKey={process.env.token}
  effect-profile={['_logo']}
  height={250}
  width={400}
  onProcessed={() => setIsReadyToSubmit(true)}
  onRef={(ref) => setRecorder(ref)}
  onVerified={(e) => saveVideo(e)}
  rerecordable={false}
  tags={[userTag]}
  theme={'elevate'}
  timelimit={180}
/>
```
Screenshot:
![image](https://user-images.githubusercontent.com/39137653/89087315-c259ea00-d348-11ea-8d55-f6f27d2cf126.png)

I tried downgrading react-ziggeo's version to 4.2.2 and when I did the error didn't show up anymore. 

Let me know if you have any questions or if I'm doing something wrong! 

Thank you for your time and help!

**Comment by sambua** [comment]
Hello @annaPerdomo ,

Could you please advice if you see any Console or Network error. This most time happens when apiKey or auth settings are not correct.

Thanks in advance.

**Comment by annaPerdomo** [comment]
Hello @sambua!

Thank you for your quick response! 

Unfortunately there aren't any errors that are appearing in the Console or Network DevTools tab. The apiKey is the same across the application and we are not using authorization tokens at this time. I downgraded the version to 4.3.0 and I didn't get the 403 error anymore. While using the 4.3.1 version, the 403 error disappears if I don't use the _key property on the VideoRecorder component to set the video key. 

I'm not sure if it helps but here are the versions of React and Next.js that we are using as well:
react: 16.9
next.js: 9.4.4

Let me know if there is any other information that I can provide! 

Thank you for your help!

**Comment by sambua** [comment]
Hello @annaPerdomo ,

It only could happens if you start recording (send the request to our server) with the same key more than one time for one application token. Reason why it happens using version `4.3.1` is, because this version supports `_key` property 🙂

**Comment by ntshcalleia** [comment]
Hi @annaPerdomo,

Every video recorded with Ziggeo has its own unique identifying token, but you can also set a custom key and use it to identify the video instead. This key must be unique inside the application, so if you try to start a recorder with a key that is already in use you’ll get a forbidden error.

If you want to use the key from an existing video to let someone re-record it you should use the `video` parameter instead. 🙂
```
<VideoRecorder
  ...
  video={'_myvideokey'}
/>
```
_The underscore at the start of the string tells our system that video is a custom key, not a token._

**Comment by annaPerdomo** [comment]
Hello @ntshrocha,

Thank you for your helpful response! 
It makes a lot of sense and I understand what is happening now. 

Thank you all again for your help with this issue!
