### ISSUE TITLE
How can access setSpeed function from Player object?

### ISSUE THREAD

**Issue by kelvin-akola** [Ziggeo/react-ziggeo#77]
I have to change the speed of video player speed on my custom setting button any solution available then guide me.

**Comment by sambua** [comment]
Hello @kelvin-akola ,

Currently, you can set our player settings button content with below example (player is ref of player element):
```
    player.addSettingsMenuItem({
        id: 'playerspeeds',
        label: 'player-speed',
        value: 1.0,
        options: [1, 5, 10], <-- HERE, YOUR SETTINGS
        func: (settings, value, index) => {
          if (typeof this.functions.set_speed === 'function' && value > 0) {
            this.functions.set_speed.call(this, value);
            return true;
          } else {
            console.error('Wrong argument or function provided');
            return false;
          }
        }
      });
```

Currently it's not supported direct call like `player.set_speed()` but now added in beta version will be available with the next releases.

**Comment by kelvin-akola** [comment]
@sambua Thanx for your response it's work for me.
