### ISSUE TITLE
What version of Ziggeo codes is being used - stable tag or some other revision?

### ISSUE THREAD

**Issue by Abdulrohman-Alakrad** [Ziggeo/react-ziggeo#78]
which version is the stable version react (npm) because i have console message im using prerelased version

**Comment by Bane-D** [comment]
Hi there,

I would just like to point out that all of our versions that are released publicly have passed our tests and are considered stable. With that said we do have a specific "stable" keyword tag that we use to allow our customers to keep their system updated without any changes from them. This is accomplished by us moving the "stable" keyword to point to a different version.

Now with that said, let us talk about what we use on React side.

We use our publicly available JS SDK https://github.com/Ziggeo/ziggeo-client-sdk in this React SDK and we call for it from here: https://github.com/Ziggeo/react-ziggeo/blob/master/package.json#L76

At this time that says:
> "ziggeo-client-sdk": "2.35.22"

What you can then do is to go to this page: https://ziggeo.com/docs/sdks/javascript/version-history

There are the very top we can currently see the following:

> stable | Latest stable build |   | Always points to the latest stable build (currently: r35)

Right under it you can also see that we have r36 as well as r37 (development) available.

So if you are using our latest React SDK you should be using our JS SDK v2.35.22 which is stable and you should not see any warnings.

Please do check these out and let us know how it goes.
