### ISSUE TITLE
How to catch error from Ziggeo when permission denied from user (whether microphone or camera)

### ISSUE THREAD

**Issue by Abdulrohman-Alakrad** [Ziggeo/react-ziggeo#80]
I'm trying to catch error when the user block camera or mic by using onError event but im stile getting Error in console which is "" uncaught (in promise) DOMException: Permission denied ""

**Comment by Bane-D** [comment]
Hi Abdulrohman,

Depending on what you would like to catch you would need to listen to different events:

```
onError
onAccessForbidden
onAccessGranted
onCameraUnresponsive
onNoCamera
onNoMicrophone
```
Specifically for not being given rights you should be listening to the `onAccessForbidden`.

Hope this helps.
