### ISSUE TITLE
Multiple Apps does not store the video differently

### ISSUE THREAD

**Issue by Piyush-Use-Personal** [Ziggeo/react-ziggeo#83]
Hey, I have encountered an issue while using the library. The issue goes like I have 2 different applications under my Ziggeo account and I have set up 2 components for both the Apps but when I record the video but It is storing both the video under the first application/default only. 
below is code for the common component I am using
```
 <ZiggeoRecorder
          apiKey={API_KEY_OF_FIRST_APP}
          height={180}
          width={320}
          onRef={(ref) => this.setRecorder(ref)}
          allowupload={false}
          onVerified={this.recorderVerified}
          onUploaded={this.recorderUploaded}
   />
 <ZiggeoRecorder
          apiKey={API_KEY_OF_SECOND_APP}
          height={180}
          width={320}
          onRef={(ref) => this.setsecondaryRecorder(ref)}
          allowupload={false}
          onVerified={this.recorderVerified}
          onUploaded={this.recorderUploaded}
   />

```
I am not really sure why is this happening but I have tested that the props are different for both the apps when passing to the component. It is quite an urgent bug so I'm really looking forward to the replies. Thanks

**Comment by ntshcalleia** [comment]
Hi @Piyush-Use-Personal, the `apiKey` property is used to define the default application, which is then used on all embeddings on the page. You can have multiple applications running at the same time on the page, but unfortunately only one can be selected as default.

If you need to have a recorder from a different application then the `application` [parameter](https://ziggeo.com/docs/sdks/javascript/browser-integration/parameters) might help, it's used to override the application token on embedding level. 🙂
 ```jsx
<ZiggeoRecorder
          application={API_KEY_OF_SECOND_APP}
          height={180}
          width={320}
          onRef={(ref) => this.setsecondaryRecorder(ref)}
          allowupload={false}
          onVerified={this.recorderVerified}
          onUploaded={this.recorderUploaded}
/>
```

**Comment by Piyush-Use-Personal** [comment]
@ntshcalleia That's Great! It worked. Thanks a lot for your help, I'm really glad. You have gained a new star 👍
