### ISSUE TITLE
On iOS allowupload={false} does not work

### ISSUE THREAD

**Issue by Piyush-Use-Personal** [Ziggeo/react-ziggeo#84]
Hey, While integrating Ziggeo into the app I encountered another issue which is
When is view the app on iOS(chrome/safari) App work differently
here is the preview of the behavior

I have `allowupload={false}` in the code but still, I'm receiving the upload button

![image](https://user-images.githubusercontent.com/75172719/124703194-75df3d00-df0f-11eb-97e3-b958fa0e4ea8.png)
and I am using the code
```
<ZiggeoRecorder
          application={API_KEY}
          height={180}
          width={320}
          onRef={(ref) => this.setRecorder(ref)}
          allowupload={false}
          onVerified={this.recorderVerified}
          onUploaded={this.recorderUploaded}
   />
```

**Comment by ntshcalleia** [comment]
Hi @Piyush-Use-Personal, I couldn't reproduce this with the demo application. If you could please send a link where we can test your recorder to support@ziggeo.com or try reproducing it with the project on the demo folder that'd be really helpful. 🙂

<img src="https://user-images.githubusercontent.com/5845648/124806927-9c16d400-df33-11eb-948e-b9138feb171f.png" width="300">

**Comment by Piyush-Use-Personal** [comment]
Sorry for the late reply, I will be asking for the video or similar confirmation to user and updating the same comment
