### ISSUE TITLE
How to check that the RECORDER has been loaded to the DOM

### ISSUE THREAD

**Issue by eokwukwe** [Ziggeo/react-ziggeo#85]
I am trying to ensure that the recorder has been loaded to the DOM before showing some elements to improve the user experience. What `event` do I need to listen to know when the recorder is loaded. I tried using the `onLoaded` event, but it is not working.

**Comment by ntshcalleia** [comment]
Hi @eokwukwe, can you try with onAttached? It's fired when the recorder is attached to the DOM. 🙂
You can find more information about events on our JS SDK documentation:
https://ziggeo.com/docs/sdks/javascript/browser-interaction/events

**Comment by eokwukwe** [comment]
@ntshcalleia The `onAttached` event only fires when the `Record Video` button is clicked.

However, the recorder container that contains the `Record Video` button takes some seconds to load on the page. Is there a way to track when the container is loaded on the page? I assumed that is what the `onLoaded` event is meant for but it does not work.

I want to make sure that other page contents do not load until the recorder is loaded with the `Record Video` button.

**Comment by ntshcalleia** [comment]
Hi @eokwukwe, you're right, I forgot this is only fired when the recorder is attached, not on the previous screen with the buttons to select type of recording. 😬 I looked into the code and the `onLoaded` event is only available on the video player at the moment, we'll be adding it to the recorder as well.

**Comment by sambua** [comment]
Hello @eokwukwe ,

If your are using hooks, how about like as below ? It will set recorder state as soon as Recorder itself will be mounted. 

```
     const [recorder, setRecorder] = useState(null);

    useEffect(() => {
        if (recorder) {
           // all user experience code is here
        }
     }, [recorder]);
    
     return(
            <ZiggeoRecorder
                apiKey={API_KEY}
                onRef={e => setRecorder(e)}
            />
    );

```

**Comment by Bane-D** [comment]
Hi there Okwukwe, just wanted to let you know that we have creted a feature request for this here: https://feedback.ziggeo.com/embeddings/p/extending-support-for-onloaded-event

* We will be updating this issue as well, however you can see other feature requests on the above mentioned feedback.ziggeo.com as well as create your own, regardless of the SDK. :)

**Comment by eokwukwe** [comment]
Thank you  @sambua. That approach solves the issue for now.

Thank you @ntshcalleia and @Bane-D. I greatly appreciate your responses. Looking forward to when the issue will be resolved.

**Comment by ntshcalleia** [comment]
Latest version of the JS SDK now supports `loaded` event on all embeds. 🙂
The React SDK is using the stable version (2.36.12), but you can update to the latest one by following these steps:
https://github.com/Ziggeo/react-ziggeo#upgrade-ziggeo-sdk
