### ISSUE TITLE
getting video duration

### ISSUE THREAD

**Issue by clement-lta** [Ziggeo/react-ziggeo#90]
When I try to upload a video or recorder. I can not video duration. it always return null.

![image](https://user-images.githubusercontent.com/59688529/153193827-0b0a1889-1593-457f-94ce-caa23308da68.png)

here is my config. Looks like any config breaks the duration feature?
```
<Recorder
              theme={theme}
              themecolor={themeColor}
              allowupload={recorderSettings.allowUpload}
              timelimit={recorderSettings.timelimit}
              faceoutline={recorderSettings.faceoutline}
              skipinitialonrerecord={recorderSettings.skipinitialOnRerecord}
              picksnapshots={recorderSettings.pickSnapshots}
              gallerysnapshots={recorderSettings.gallerySnapshots}
              countdown={recorderSettings.countdown}
              title={customData.name}
              custom-data={customData}
              tags={[customData.name, customData.company, customData.customerId]}
              video-profile={recorderSettings.hd ? process.env.REACT_APP_VIDEO_PROFILE : undefined}
              recordingwidth={recorderSettings.hd ? 960 : 640}
              recordingheight={recorderSettings.hd ? 720 : 480}
              onProcessed={handleRecorderProcessedEvent}
              onRef={(ref: any) => setRecorder(ref)}
/>
```

**Comment by ntshcalleia** [comment]
Hi @tuananh96gl, which version of the JS SDK you’re using? You can check it by going to the console and typing `ZiggeoApi.V2.Device.info.revision`.

Before r39 we got the `video_data` once - before recording starts - and then this value wasn't updated after the video was processed. On r39 we are actively listening for changes and updating the `video_data` after we receive new data from the servers. If you're on r39 once the video is processed you should be able to see the correct duration.

You could also try using `recorder.get("duration")`, this is calculated on the client-side after recording. The data that comes from `video_data` is more reliable, though.

**Comment by clement-lta** [comment]
Thanks @ntshcalleia for your reply.
My version is r36. I tried to upgrade to newest version and it works. Thank you so much!
