### ISSUE TITLE
Can not record when the video recorder is in modal dialog

### ISSUE THREAD

**Issue by naka-go** [Ziggeo/react-ziggeo#91]
When I put a video recorder in a dialog. I got a permission error
![image](https://user-images.githubusercontent.com/105287491/173571614-cd09ffff-955e-491a-94a0-ae7c5f1103d3.png)

**Comment by ntshcalleia** [comment]
Hi @naka-go, can you please send us a code example so we can try to reproduce this?

**Comment by naka-go** [comment]
Thanks @ntshcalleia 
That's my fault. we don't put the `allow` attributes in the iframe
