### ISSUE TITLE
React ziggeo still able to upload other files  and manual upload not working

### ISSUE THREAD

**Issue by amp-taledo** [Ziggeo/react-ziggeo#92]
As i checked react ziggeo only makes accept attribute in input element. Which is not enough as if user changes file type in upload dialog then user can select any file. In this case it starts uploading and in verify stage it goes infinite. 

No error handling in verify stage , No type check validation before uploading.

I tried by manually but upload_video throws an error state of undefined. 

We are using license version of ziggeo but we can't even customize this small and important thing.

<img width="498" alt="Screenshot 2022-06-14 at 6 07 57 PM" src="https://user-images.githubusercontent.com/101424442/173578914-684669c3-d30a-4550-bb25-f97dd4f0ff20.png">

**Comment by ntshcalleia** [comment]
Hi @amp-taledo, by default the recorder allows uploading files of any format, but you can restrict it to only allow video files by setting `allowcustomupload` to false:
https://ziggeo.com/docs/sdks/javascript/browser-integration/parameters

**Comment by amp-taledo** [comment]
@ntshcalleia I already set allowcustomupload to false. But when system upload dialog comes you can change it to all files and it will allow to upload any file.
See here: You can change format to all files and it will allow.

<img width="815" alt="Screenshot 2022-06-14 at 8 00 33 PM" src="https://user-images.githubusercontent.com/101424442/173603246-1fa35b32-49cb-40d2-8d45-9c9280ddad6a.png">

**Comment by Bane-D** [comment]
Hi Amit,

The `allowedextensions` parameter should allow you to set specific file types to be uploaded and then limit the system dialog as well by passing those values over.

That said, we are currently aware of an issue, where with the same you might still be able to upload different files in certain scenarios and are looking to fix this.

Unfortunately you have to set all the file types in that case, you can not set "videos" or "audios" and have it automatic in a way. If you feel like that would be better, feel free to post about it here: https://feedback.ziggeo.com.

**Comment by Bane-D** [comment]
The `allowedextensions` parameter would assist with the same and has been updated to address the issue mentioned in the comment above. Due to both, I am closing this issue.

* Please note that at this time the update is available only on the latest version of our system, so you might need to follow steps here: https://github.com/Ziggeo/react-ziggeo#upgrade-ziggeo-sdk to have the updated version of the parameter.
