### ISSUE TITLE
microphonehealth event

### ISSUE THREAD

**Issue by MariaShyn** [Ziggeo/react-ziggeo#94]
Hi! Do you have support for embedded event 'microphonehealth' event?

**Comment by MariaShyn** [comment]
and has_microphone?

**Comment by Bane-D** [comment]
Hi Maria,

Doing a quick look I can see we show `onNoMicrophone` as available and that all events should be supported from our JS SDK (which would mean that we should support `no_microphone`, `has_microphone` and `microphonehealth`).

I am checking with my colleague that is working on React side to see if it is available or if an update needs to be made of any kind.

**Comment by MariaShyn** [comment]
thank you! so I will try onHasMicrophone and onMicrophonehealth as well

**Comment by MariaShyn** [comment]
onMicrophonehealth and onHasMicrophone are 'Unknown event handler property'

**Comment by Bane-D** [comment]
Thank you for checking Maria. I believe that we need to add all of those to this list first: https://github.com/Ziggeo/react-ziggeo/blob/d4f7cec4376837c5e0c64087a4d46f2d63d282c1/src/constants.js#L409

Waiting for my colleague working with React to get a chance to inspect things and will then follow up with more details.

**Comment by sambua** [comment]
Hello @MariaShyn , unfortunately hasMic and hasCamera related events are working little bit different. 
Only one of them are dispatching noMicrophone or hasMicrophone (as well noCamera or hasCamera) not together. So why this confusion happens. In the feature we can add some additional events where result will be true/false based on cam and mic status.

Regarding missing events below events will be added to the next release:
```
  onMicrophonehealth
  onCamerahealth
  onCameraSignal
  onBound
  onHasCamera
  onHasMicrophone
  onRecordingStopped
  onStopped
  onReadyToRecord
```

**Comment by MariaShyn** [comment]
perfect, thanks, so waiting for the next release! :)

**Comment by sambua** [comment]
Hello @MariaShyn new release `4.6.1` already published. 

Please be aware that you'll get 2 arguments on onMicrophonehealth , first attributes second boolean value. 

Have a good coding :)
