### ISSUE TITLE
ZiggeoRecorder crashes on recording start

### ISSUE THREAD

**Issue by techyvish** [Ziggeo/react-ziggeo#97]
Hi I'm using React-Ziggeo in my Next.js project and seeing this crash while using this SDK.  What's the correct way to setup this on Next projects and how can I resolve this?

<img width="704" alt="Screen Shot 2022-09-07 at 11 56 22 AM" src="https://user-images.githubusercontent.com/1515831/189064212-6e1f5a58-bba3-4b4d-a604-349e91123a8e.png">

    `const ZiggeoRecorder = dynamic(
      () =>
        import('react-ziggeo').then((app) => {
          return app.ZiggeoRecorder
        }),
      { ssr: false },
    )

    <ZiggeoRecorder
      apiKey={process.env.NEXT_PUBLOC_ZIGGEO_KEY}
      allowscreen={false}
      allowrecord={true} // Optional you can even set it to true
      allowupload={false}
      height={640}
      width={'100%'}
      theme={'modern'}
    />`

"react-ziggeo": "^4.6.2"
"next": "12.1.0"

**Comment by Bane-D** [comment]
Hi Patel,

Based on the error you should check the value you are providing in `process.env.NEXT_PUBLOC_ZIGGEO_KEY`. It should be your app_token (you can get it by logging into your account and then going to Overview page of the app you want to use).

**Comment by techyvish** [comment]
Thanks, there was issue with the key.
